window.BOUNCE_EJ_CHARACTERS = [
  {
    "id": "regular",
    "name": "Regular EJ",
    "file": "Regular EJ.png",
    "price": 0,
    "section": "EJs",
    "limitedTime": false,
    "fill": "#35c2ff",
    "face": "#061019",
    "ring": "#ffffff",
    "rarity": "Common"
  },
  {
    "id": "lowres",
    "name": "Low Res EJ",
    "file": "Low Res EJ.png",
    "price": 20,
    "section": "EJs",
    "limitedTime": false,
    "fill": "#f5c542",
    "face": "#3d2700",
    "ring": "#fff4b8",
    "rarity": "Common"
  },
  {
    "id": "silly",
    "name": "Silly EJ",
    "file": "Silly EJ.png",
    "price": 20,
    "section": "EJs",
    "limitedTime": false,
    "fill": "#ff36d3",
    "face": "#120018",
    "ring": "#45ff87",
    "rarity": "Common"
  },
  {
    "id": "portrait",
    "name": "Portrait EJ",
    "file": "Portrait EJ.png",
    "price": 20,
    "section": "EJs",
    "limitedTime": false,
    "fill": "#2d3342",
    "face": "#ffffff",
    "ring": "#8993a6",
    "rarity": "Uncommon"
  },
  {
    "id": "ethan",
    "name": "Ethan",
    "file": "Ethan EJ.png",
    "price": 100,
    "section": "Friends",
    "limitedTime": false,
    "fill": "#5ee085",
    "face": "#061019",
    "ring": "#ffffff",
    "rarity": "Uncommon"
  },
  {
    "id": "victor-chud",
    "name": "Victor Chud",
    "file": "VictorChud.png",
    "price": 30,
    "section": "Friends",
    "limitedTime": false,
    "fill": "#ff6b6b",
    "face": "#000000",
    "ring": "#ffffff",
    "rarity": "Legendary"
  },
  {
    "id": "kevin",
    "name": "Kevin",
    "file": "Kevin.png",
    "price": 1000000,
    "section": "Friends",
    "limitedTime": true,
    "fill": "#ff6b6b",
    "face": "#000000",
    "ring": "#ffffff",
    "rarity": "Legendary"
  },
  {
    "id": "diana",
    "name": "DianaHolly",
    "file": "DianaHolly.png",
    "price": 20,
    "section": "Friends",
    "limitedTime": false,
    "fill": "#ff6b6b",
    "face": "#000000",
    "ring": "#ffffff",
    "rarity": "Common"
  },
  {
    "id": "espi",
    "name": "Espi",
    "file": "Espi.png",
    "price": 20,
    "section": "Limited",
    "limitedTime": false,
    "fill": "#ff6b6b",
    "face": "#000000",
    "ring": "#ffffff",
    "rarity": "Legendary"
  },
  {
    "id": "leo",
    "name": "Leo",
    "file": "Leo.png",
    "price": 20,
    "section": "Friends",
    "limitedTime": false,
    "fill": "#ff6b6b",
    "face": "#000000",
    "ring": "#ffffff",
    "rarity": "Rare"
  },
  {
    "id": "bald",
    "name": "Bald EJ",
    "file": "Bald.png",
    "price": 20,
    "section": "EJs",
    "limitedTime": false,
    "fill": "#ff6b6b",
    "face": "#000000",
    "ring": "#ffffff",
    "rarity": "Common"
  },
  {
    "id": "schabel",
    "name": "Schabel",
    "file": "Schabel.png",
    "price": 20,
    "section": "Friends",
    "limitedTime": false,
    "fill": "#ff6b6b",
    "face": "#000000",
    "ring": "#ffffff",
    "rarity": "Legendary"
  },
  {
    "id": "stone",
    "name": "Stone",
    "file": "Stone.png",
    "price": 500,
    "section": "Friends",
    "limitedTime": false,
    "fill": "#ff6b6b",
    "face": "#000000",
    "ring": "#ffffff",
    "rarity": "Legendary"
  },
  {
    "id": "ryan",
    "name": "Ryan",
    "file": "Ryan.png",
    "price": 499,
    "section": "Friends",
    "limitedTime": false,
    "fill": "#ff6b6b",
    "face": "#000000",
    "ring": "#ffffff",
    "rarity": "Rare"
  },
  {
    "id": "stone2",
    "name": "Stone 2.0",
    "file": "FlyStone.png",
    "price": 250,
    "section": "Friends",
    "limitedTime": false,
    "fill": "#e886f1",
    "face": "#000000",
    "ring": "#fbccff",
    "rarity": "Legendary"
  }
];
